# Generated by Django 5.2.1 on 2025-05-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
