# Generated by Django 5.2.1 on 2025-05-19 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entidadAdministradoraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dni_rep_legal', models.CharField(max_length=20, unique=True)),
                ('p_nombre_rep_legal', models.CharField(max_length=50)),
                ('s_nombre_rep_legal', models.CharField(max_length=50)),
                ('p_apellido_rep_legal', models.CharField(max_length=50)),
                ('s_apellido_rep_legal', models.CharField(max_length=50)),
                ('ubicacion_oficina', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFocalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador EAS'), ('madre', 'Madre Comunitaria')], max_length=20)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('id_eas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indata.entidadadministradoraservicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cuentame', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
                ('id_eas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indata.entidadadministradoraservicio')),
                ('id_madre', models.ForeignKey(limit_choices_to={'tipo': 'madre'}, on_delete=django.db.models.deletion.CASCADE, to='app_indata.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Infante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('p_nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('p_apellido', models.CharField(max_length=50)),
                ('s_apellido', models.CharField(max_length=50)),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indata.tipodni')),
                ('tipo_focalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indata.tipofocalizacion')),
                ('id_uds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indata.unidadservicio')),
            ],
        ),
    ]
