# Generated by Django 5.2.1 on 2025-05-28 03:41

import app_indata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadadministradoraservicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=app_indata.models.eas_image_upload_path),
        ),
    ]
