# Generated by Django 5.2.1 on 2025-05-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_indata', '0002_entidadadministradoraservicio_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadadministradoraservicio',
            old_name='imagen',
            new_name='logo',
        ),
    ]
