# Generated by Django 5.2.1 on 2025-05-28 03:55

import app_indata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indata', '0003_rename_imagen_entidadadministradoraservicio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infante',
            name='documento_focalizacion',
            field=models.FileField(blank=True, null=True, upload_to=app_indata.models.infante_documento_focalizacion_upload_path),
        ),
    ]
